name: mapbox_search
description: A Flutter package for place search using MapBox Api and for Static map image
version: 3.2.0

homepage: https://github.com/ketanchoyal/mapbox_search

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.0

dev_dependencies:

